import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Helvetica = localFont({
  src: '../public/fonts/Helvetica/Helvetica.woff2',
  weight: '400',
  style: 'normal',
  variable: '--font-helvetica',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Helvetica.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
